SchoolSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = 'home'),
    path('accounts/', include("accounts.urls")),
    path('teachers/', include('teacher.urls')),
    path('students/', include('students.urls'))
]

teacher/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'teacher'
urlpatterns = [
    path('update/<int:pk>/', views.TeacherUpdate.as_view(), name = 'update'),
    path('detail/<int:pk>/', views.TeacherDetails.as_view(), name = 'detail'),
    path('create/test/', views.CreateTest.as_view(), name = 'test_create'),
    path('tests/details/<int:pk>/', views.TestDetails.as_view(), name = 'test_details'),
    path("tests/<int:pk>", views.TestDetails.as_view(), name  = 'class_grading'),
    path("class/<int:pk>", views.ClassDetails.as_view(), name  = 'class'),
]

teacher/models.py
from django.db import models
from django.contrib.auth.models import User
from students.models import Classes, Student
# Create your models here.
SUBJECTS = (('English', 'English'), ('Maths','Maths'), ('PE','PE'), ('History','History'), ('Biology','Biology'), ('Physics','Physics'))

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    teacher = models.BooleanField(default=False)
    subject = models.CharField(max_length=10, choices=SUBJECTS)
    form_teacher = models.CharField(max_length = 5, blank = True ,default = False)
    classes = models.ManyToManyField(Classes, related_name='teacher_classes')

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

class Tests(models.Model):
    teacher = models.ForeignKey(Teacher,on_delete=models.CASCADE, null = True)
    desc = models.CharField(max_length = 50, null = True)
    student = models.ForeignKey(Student, on_delete = models.CASCADE, null = True)
    subject = models.CharField(max_length=10, choices=SUBJECTS, null = True)
    classes = models.ForeignKey(Classes, on_delete = models.CASCADE, null = True)
    created_at = models.DateTimeField(auto_now=True)
    planned = models.DateField(null = True)
    class Grades(models.IntegerChoices):
        F = 1
        E = 2
        D = 3
        C = 4
        B = 5
        A = 6

    grade = models.IntegerField(choices = Grades.choices, null = True)
    def __str__(self):
        return self.desc
    class Meta:
        ordering = ["-created_at"]

teacher/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Tests
from students.models import Classes
from django.contrib.admin import widgets
classes = Classes.objects.all()
classes = list(classes)
CLASSES = []
for clas in classes:
    CLASSES.append((clas , clas.name))


SUBJECTS = ((1, "F"), (2,"E"), (3,"D"), (4, "C"), (5,"B"), (6,"A"))
class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'password',
        ]

class TestForm(forms.ModelForm):
    class Meta:
        model = Tests
        fields = ('desc', 'classes','planned')
        labels = {
        "desc": 'Description',
        'classes': "Class",
        'planned': "Date [Y-M-D]"    
    }

teacher/views.py
from django.shortcuts import render
from django.views.generic.edit import UpdateView
from django.views.generic import DetailView, CreateView, ListView, FormView
from .models import Teacher, Tests
from django.urls import reverse_lazy
from SchoolSystem.views import WhichUserMixin
from students.models import Classes, Student
from django import forms
from django.db import models
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.
class TeacherUpdate(WhichUserMixin, UpdateView):
    model = Teacher
    fields = ['subject', 'form_teacher', 'classes']
    template_name = 'updat.html'
    success_url = reverse_lazy('home')


class TeacherDetails(WhichUserMixin, DetailView):
    template_name = 'teacher_detail.html'
    model = Teacher
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        classes = list(self.current_teacher.classes.all())
        context['classes'] = classes
        tests = Tests.objects.filter(grade__isnull = False, teacher = self.current_teacher)
        graded_tests = tests.values_list('classes', 'desc')
        list(graded_tests)
        graded_tests_classes = []
        for tup in graded_tests:
            if tup not in graded_tests_classes:
                graded_tests_classes.append(tup)
        graded_tests = []
        for tup in graded_tests_classes:
            graded_tests.append(Tests.objects.filter(grade__isnull = False, teacher = self.current_teacher, classes = tup[0], desc = tup[1]).first())
        context['tests'] = graded_tests[:6]
        return context

class TestForm(forms.ModelForm):
    class Meta:
        model = Tests
        fields = ['desc', 'classes', 'planned']
        labels = {
        "desc": 'Description',
        'classes': "Class",
        'planned': "Date [Y-M-D]"
    }


class CreateTest(WhichUserMixin, CreateView):
    model = Tests
    form_class = TestForm
    template_name = 'create_test.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        test = form.save(commit=False)
        teacher = Teacher.objects.get(user = self.request.user)
        class_name = form.cleaned_data['classes']
        desc =  form.cleaned_data['desc']
        planned = form.cleaned_data['planned']
        classes = Classes.objects.get(name = class_name)
        students = classes.students.all()
        students_list = list(students)
        if len(students_list)>1:
            students = students_list.pop()
            print(students)
            for student in students_list:
                Tests.objects.create(desc=desc, teacher = teacher, classes = classes, student = student, subject = teacher.subject, planned = planned )
                print('test created for: ' + student.user.username)
        test.teacher = teacher
        test.subject = teacher.subject
        test.planned = planned
        test.student = students.first()
        print('test created for: ' + test.student.user.username)
        return super(CreateTest, self).form_valid(form)


class ClassDetails(WhichUserMixin, DetailView):
    model = Classes
    template_name = 'class_details.html'
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        students = list(self.get_object().students.all())
        context['students'] = students
        students_tests = Tests.objects.all().filter(teacher = self.current_teacher, classes = self.get_object(), grade__isnull = False)
        context['students_tests'] = students_tests
        means_list = []
        for student in students:
            student_tests = list(students_tests.filter(student = student))
            mean = 0
            i = 0
            for test in student_tests:
                i += 1
                mean += int(test.grade)
            if i != 0:
                num = mean/i
                mean = "{:.2f}".format(num)
                mean = [mean, student]
            else:
                mean = ['None', student]
            means_list.append(mean)
        context['means_list'] = means_list
        return context





SUBJECTS = ((1, "F"), (2,"E"), (3,"D"), (4, "C"), (5,"B"), (6,"A"))

class GradeForm(forms.Form):
    model = Tests
    grade = forms.ChoiceField(choices = SUBJECTS)

class TestDetails(WhichUserMixin, DetailView):
    model = Tests
    template_name = "class_test_details.html"
    success_url = reverse_lazy('home')
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        tests = Tests.objects.all().filter(grade = None, classes = self.get_object().classes, desc = self.get_object().desc, teacher = self.current_teacher)
        context['ungraded_tests'] = tests
        context['form'] = GradeForm()
        return context

    def post(self, request,*args, **kwargs):
        teachers = Teacher.objects.all()
        students = Student.objects.all()
        teacher_list = []
        students_list = []
        for teacher in teachers:
            teacher_list.append(teacher.user.username)
        for student in students:
            students_list.append(student.user.username)
        if self.request.user.is_authenticated and self.request.user.username in teacher_list:
            self.current_teacher = Teacher.objects.get(user = self.request.user)
            self.current_student = None
        test = Tests.objects.all().filter(grade = None, teacher = self.current_teacher,  desc = self.get_object().desc,  classes = self.get_object().classes)
        grades = request.POST.getlist('grade')
        i = 0

        for test_l in list(test):
            for element in SUBJECTS:
                if int(element[0]) == int(grades[i]):
                    print(element[0])
                    test_l.grade = int(element[0])
                    test_l.save()
            i += 1
        return HttpResponseRedirect(reverse_lazy('home'))

teacher/templates/class_details.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<h1>{{classes.name}}</h1>
<div id="teacher" class="clear">
  <div class="test">
{% for student in students %}
<div class="col-md-3">
<h3>{{student.user.first_name}} {{student.user.last_name}}</h3>
{% for test in students_tests %}
{% if test.student == student %}
<p>{{test.desc}} - {{test.grade}}<p>
{% endif %}
{% endfor %}
{% for mean in means_list %}
{% if mean.1 == student %}
<h3>Mean from all tests: {{mean.0}}</h3>
{% endif %}
{% endfor %}
</div>
{% endfor %}

</div>

{% endblock %}

teacher/templates/class_test_details.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap3 %}
    <div class="col-md-6">
    <h2>Class:   </h2>
    </div>
    <div class="col-md-6">
    <h2>Test: {{test.desc}} </h2>
    </div>
    <div id="teacher" class="clear">
      <div class="test">
    <form method="post">

    {% for test in ungraded_tests  %}

    <div class="col-md-6">
    <h3> <a href="{% url 'teacher:test_details' pk=test.pk %}">{{test.student.user.first_name}} {{test.student.user.last_name}}</a></h3>
    </div>
    <div class="col-md-1">
      {% csrf_token %}
      {% bootstrap_form form  %}
    </div>
    {% endfor %}
    <br>
    <input type="submit" class="signup" value="Submit">
    </form>
{% endblock %}

teacher/templates/create_test.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <h1>Create test:</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form  %}
    <input type="submit" class = 'btn btn-default' value="Sign up">
  </form>
</div>

{% endblock %}

teacher/templates/grade_tests.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
  <h1>Grade tests:</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form  %}
    <input type="submit" class = 'btn btn-default' value="Sign up">
  </form>
</div>

{% endblock %}

teacher/templates/teacher_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <h1>Your profile:</h1>
  <div id="teacher" class="clear">
  <div class="test">
    <div class="col-md-4">
    <h3> First and last name:</h3>
    <h3> Subject:</h3>
    <h3> Classes: </h3>

    </div>
    <div class="col-md-4">
    <h3>{{teacher.user.first_name}} {{teacher.user.last_name}}</h3>
    <h3>{{teacher.subject}}</h3>
    {% for class in classes %}
    <h3><a href="{% url 'teacher:class' pk=class.pk  %}">{{class.name}}</a></h3>
    {% endfor %}
    </div>
  <a class="signup" href="{% url 'teacher:update' pk=teacher.pk %}">Update infos!</a>
</div>
</div>
<h1>Last graded tests:</h1>
<div id="teacher" class="clear">
<div class="test">
{% for test in tests %}
<div class="col-md-4">
  <h3> Class: {{test.classes}} </h3>
  <p>{{test.teacher.subject}} - {{test.desc}}</p>
</div>
{% endfor %}
</div>
</div>
</div>

{% endblock %}

teacher/templates/teacher_index.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap3 %}
    <h1>  Welcome {{user.first_name}} to EduSys!</h1>
    <div class="col-md-4">
      <h2>Your ungraded tests: </h2>
      {% for test in ungraded_tests %}
        <div id="teacher" class="clear">
          <div class="test">
            <h3> Class: {{test.classes}} </h3>
              <p>{{test.teacher.subject}} - {{test.desc}}</p>
            <a class="signup" href="{% url 'teacher:class_grading' pk=test.pk  %}">Go to!</a>
          </div>
          </div>
    {% endfor %}
    </div>

    <div class="col-md-4">
    <h2> Schedulded tests: </h2>
    {% for test in planned_tests %}
      <div id="teacher" class="clear">
        <div class="test">
          <h3> Class: {{test.classes}} </h3>
            <p>{{test.teacher.subject}} - {{test.desc}}</p>
          <a class="signup" href="{% url 'teacher:class_grading' pk=test.pk  %}">Go to!</a>
        </div>
        </div>
  {% endfor %}
    </div>

    <div class="col-md-4">
    <h2> Create test: </h2>
    <div id="teacher" class="clear">
    <div class="test">
      <form method="post">
      {% csrf_token %}
      {% bootstrap_form form  %}

      <input type="submit" class ="signup" value="Sign up">

      </form>
    </div>
    </div>
    </div>


{% endblock %}

teacher/templates/tests_update.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <h1>Sign up</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form  %}
    <input type="submit" class = 'btn btn-default' value="Create">
  </form>
</div>

{% endblock %}

teacher/templates/updat.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <h1>Update</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form  %}
    <input type="submit" class = 'btn btn-default' value="Update">
  </form>
</div>

{% endblock %}