SchoolSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = 'home'),
    path('accounts/', include("accounts.urls")),
    path('teachers/', include('teacher.urls')),
    path('students/', include('students.urls'))
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html', success_url='home'), name = 'login' ),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('signup/', views.SignUp.as_view(), name = 'signup')
]

students/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'students'
urlpatterns = [
    path('detail/<int:pk>/', views.StudentsDetails.as_view(), name = 'detail'),
    path('grades/<str:str>/', views.StudentsGrades.as_view(), name = 'grade')
    ]

teacher/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'teacher'
urlpatterns = [
    path('update/<int:pk>/', views.TeacherUpdate.as_view(), name = 'update'),
    path('detail/<int:pk>/', views.TeacherDetails.as_view(), name = 'detail'),
    path('create/test/', views.CreateTest.as_view(), name = 'test_create'),
    path('tests/details/<int:pk>/', views.TestDetails.as_view(), name = 'test_details'),
    path("tests/<int:pk>", views.TestDetails.as_view(), name  = 'class_grading'),
    path("class/<int:pk>", views.ClassDetails.as_view(), name  = 'class'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>EduSys</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/master.css'%}"/>


  </head>


  <body>

    <nav class="navbar" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand" href="{% url 'home' %}">Home Page</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                {% if current_teacher != None %}
                <li><a href="{% url 'teacher:detail' pk=current_teacher.pk %}" class="btn btn-simple">My Profile</a></li>
                <li><a href="{% url 'teacher:test_create'%}" class="btn btn-simple">Create Test</a></li>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle btn-simple" href="#" id="navbardrop" data-toggle="dropdown">My Classes</a>
                <div class="dropdown-menu">
                  <ul>
                  {% for class in classes %}
                  <li class ="btn-simple"><a class="dropdown-item" href="{% url 'teacher:class' pk=class.pk %}">{{class.name}}</a></li>
                  {% endfor %}
                </ul>
                </div>
              </li>

                {% endif %}
                {% if current_student != None %}
                <li><a href="{% url 'students:detail' pk=current_student.pk %}" class="btn btn-simple">My Profile</a></li>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle btn-simple" href="#" id="navbardrop" data-toggle="dropdown">My grades</a>
                <div class="dropdown-menu">
                  <ul>
                  {% for subject in subjects %}
                  <li class ="btn-simple"><a class="dropdown-item" href="{% url 'students:grade' str=subject %}">{{subject}}</a></li>
                  {% endfor %}
                </ul>
                </div>
              </li>

                {% endif %}

                <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>

    						{% else %}
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>
    			</div>
    		</nav>
        <div class="container">
          {% block content %}

          {% endblock %}

        </div>


        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome to EduSys!</h1>
    
{% endblock %}